### ISSUE TITLE
Some images from Github Readme are not shown

### ISSUE THREAD

**Issue by evshvarov** [intersystems-community/openexchange#62] opened 2019-07-26 07:45 UTC
Example one: https://openexchange.intersystems.com/package/Visualizing-the-data-jungle

Example two:
https://openexchange.intersystems.com/package/AnalyzeThis

**Comment by isc-rsingh** [comment] 2019-11-02 01:36
For https://openexchange.intersystems.com/package/Visualizing-the-data-jungle, the image doesn't exist in github either.

For https://openexchange.intersystems.com/package/AnalyzeThis, The readme file is pointing to github's page listing the file (https://github.com/psteiwer/AnalyzeThis/blob/master/Assets/AnalyzeThis_BookCover.png) not the raw file itself (https://raw.githubusercontent.com/psteiwer/AnalyzeThis/master/Assets/AnalyzeThis_BookCover.png).

**Comment by Lena-Ev** [comment] 2021-02-01 13:22
Duplicate of #143

**Closed as completed by Lena-Ev** 2021-02-01 13:22 UTC
Labels: bug
