### ISSUE TITLE
Support relative URLs to GitHub resources in Long Description markdown

### ISSUE THREAD

**Issue by dmitry-zasypkin** [intersystems-community/openexchange#184] opened 2020-10-05 06:33 UTC
Example of a relative URL in a GitHub repo description:
`[iscru.fhir.fts.FTSStrategy](../main/src/cls/iscru/fhir/fts/FTSStrategy.cls)`

Should resolve to https://github.com/intersystems-ru/fhir-terminology-service/blob/main/src/cls/iscru/fhir/fts/FTSStrategy.cls

**Comment by Lena-Ev** [comment] 2021-01-25 14:59
Duplicate of #143

**Closed as completed by Lena-Ev** 2021-01-25 14:59 UTC
